#requires -Version 5.1
<#
.SYNOPSIS
  One-command deploy/validate orchestrator for the Hearst Fabric CI/CD Terraform package.

.DESCRIPTION
  Authenticates with Azure CLI, auto-derives the mandatory parameters from your signed-in
  session, prompts only for anything it cannot derive, applies sensible defaults for optional
  settings, then runs terraform init -> validate -> plan (and optionally apply). Finally it
  generates an HTML report of exactly what Terraform planned.

  You do NOT choose which .tf file runs first: Terraform builds the dependency graph and
  orders everything automatically, so this single command IS the full sequential run.

.PARAMETER Apply
  Actually create resources (terraform apply). Omit for plan-only (safe; creates nothing).

.EXAMPLE
  ./deploy.ps1                                   # plan only; all mandatory params auto-derived
.EXAMPLE
  ./deploy.ps1 -ExistingCapacityName "My Cap"    # reuse an existing capacity instead of creating one
.EXAMPLE
  ./deploy.ps1 -Apply                            # create the resources after you have reviewed the plan
#>
[CmdletBinding()]
param(
  [string]$SubscriptionId,
  [string]$TenantId,
  [string]$AdminObjectId,
  [string]$KeyVaultName,
  [string]$CapacitySku = "F2",
  [string]$ExistingCapacityName = "",
  [bool]$DeployExampleWorkload = $true,
  [switch]$Apply,
  [switch]$AutoApprove
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot   # the infra/ folder

function Info($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Warn($m) { Write-Host "[!] $m"  -ForegroundColor Yellow }
function Die($m)  { Write-Host "[x] $m"  -ForegroundColor Red; exit 1 }

# ---------------------------------------------------------------------------
# 1) Ensure Azure CLI sign-in
# ---------------------------------------------------------------------------
Info "Checking Azure CLI sign-in..."
$acct = az account show 2>$null | ConvertFrom-Json
if (-not $acct) {
  Info "Not signed in. Launching device-code login..."
  if ($TenantId) { az login --use-device-code --tenant $TenantId | Out-Null }
  else           { az login --use-device-code | Out-Null }
  $acct = az account show 2>$null | ConvertFrom-Json
  if (-not $acct) { Die "Azure sign-in failed. Run 'az login' and retry." }
}
Info "Signed in as $($acct.user.name) | subscription: $($acct.name)"

# ---------------------------------------------------------------------------
# 2) Auto-derive mandatory parameters (prompt only if not derivable)
# ---------------------------------------------------------------------------
if (-not $SubscriptionId) { $SubscriptionId = $acct.id }
if (-not $TenantId)       { $TenantId       = $acct.tenantId }
if (-not $AdminObjectId)  { $AdminObjectId  = (az ad signed-in-user show --query id -o tsv 2>$null) }
if (-not $AdminObjectId)  { $AdminObjectId  = Read-Host "Enter admin_object_id (Entra object id to grant Admin on workspaces/Key Vault)" }

# Capacity admin: UPN for a user account, object id for a service principal
$capacityAdmin = if ($acct.user.type -eq 'user' -and $acct.user.name) { $acct.user.name } else { $AdminObjectId }

# ---------------------------------------------------------------------------
# 3) Key Vault name (must be globally unique, 3-24 chars)
# ---------------------------------------------------------------------------
if (-not $KeyVaultName) {
  $suffix = -join ((48..57) + (97..122) | Get-Random -Count 6 | ForEach-Object { [char]$_ })
  $KeyVaultName = "kvhearst$suffix"
}
if ($KeyVaultName.Length -gt 24) { $KeyVaultName = $KeyVaultName.Substring(0, 24) }

# ---------------------------------------------------------------------------
# 4) Write generated.auto.tfvars (auto-loaded by Terraform)
# ---------------------------------------------------------------------------
Info "Writing generated.auto.tfvars (mandatory values filled; optional defaulted)..."
$exampleFlag = $DeployExampleWorkload.ToString().ToLower()
$tfvars = @"
# AUTO-GENERATED by deploy.ps1 -- safe to delete/regenerate. DO NOT COMMIT (gitignored).
subscription_id        = "$SubscriptionId"
tenant_id              = "$TenantId"
admin_object_id        = "$AdminObjectId"
key_vault_name         = "$KeyVaultName"

# Capacity: leave existing_capacity_name blank to CREATE a new F-SKU capacity.
existing_capacity_name = "$ExistingCapacityName"
capacity_sku           = "$CapacitySku"
capacity_admin_members = ["$capacityAdmin"]

# Example workload (so you see real items created end-to-end).
deploy_example_workload = $exampleFlag
example_workspace       = "dev"

# Git integration off by default so a first run is fully self-contained.
enable_git_integration  = false
"@
Set-Content -Path "generated.auto.tfvars" -Value $tfvars -Encoding UTF8

Write-Host ""
Write-Host "  Resolved parameters:" -ForegroundColor Green
Write-Host "    subscription_id : $SubscriptionId"
Write-Host "    tenant_id       : $TenantId"
Write-Host "    admin_object_id : $AdminObjectId"
Write-Host "    key_vault_name  : $KeyVaultName"
Write-Host "    capacity        : $(if ($ExistingCapacityName) { "reuse '$ExistingCapacityName'" } else { "create new $CapacitySku" })"
Write-Host "    example_workload: $exampleFlag"
Write-Host ""

# ---------------------------------------------------------------------------
# 5) Terraform init -> validate -> plan
# ---------------------------------------------------------------------------
Info "terraform init..."
terraform init -input=false -no-color
if ($LASTEXITCODE -ne 0) { Die "terraform init failed." }

Info "terraform validate..."
terraform validate -no-color
if ($LASTEXITCODE -ne 0) { Die "terraform validate failed." }

Info "terraform plan (creates nothing)..."
terraform plan -input=false -no-color -out="plan.tfplan"
if ($LASTEXITCODE -ne 0) { Die "terraform plan failed (see output above)." }

# ---------------------------------------------------------------------------
# 6) Generate the run report
# ---------------------------------------------------------------------------
Info "Generating run report -> run-report.html ..."
terraform show -json "plan.tfplan" | Set-Content -Path "plan.json" -Encoding UTF8
$reportGen = Join-Path $PSScriptRoot "..\scripts\tf_run_report.ps1"
if (Test-Path $reportGen) {
  & $reportGen -PlanJsonPath (Join-Path $PSScriptRoot "plan.json") -OutHtml (Join-Path $PSScriptRoot "run-report.html")
  Info "Report ready: infra/run-report.html"
} else {
  Warn "Report generator not found at $reportGen (skipping report)."
}

# ---------------------------------------------------------------------------
# 7) Optional apply (explicit, gated)
# ---------------------------------------------------------------------------
if ($Apply) {
  if (-not $AutoApprove) {
    $c = Read-Host "APPLY will create REAL resources (a new capacity is billable). Type 'yes' to proceed"
    if ($c -ne 'yes') { Warn "Apply cancelled."; exit 0 }
  }
  Info "terraform apply..."
  terraform apply -input=false -no-color "plan.tfplan"
  if ($LASTEXITCODE -ne 0) { Die "terraform apply failed." }
}

Info "Done."
