/// fct_ad: Ad impressions, clicks, and revenue by date/brand/campaign/platform
table fct_ad
	lineageTag: 00000000-0000-0000-0000-000000000080

	/// Foreign Keys
	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 00000000-0000-0000-0000-000000000081
		sourceColumn: date_key
		summarizeBy: none

	column brand_key
		dataType: int64
		formatString: 0
		lineageTag: 00000000-0000-0000-0000-000000000082
		sourceColumn: brand_key
		summarizeBy: none

	column campaign_key
		dataType: int64
		formatString: 0
		lineageTag: 00000000-0000-0000-0000-000000000083
		sourceColumn: campaign_key
		summarizeBy: none

	column platform_key
		dataType: int64
		formatString: 0
		lineageTag: 00000000-0000-0000-0000-000000000084
		sourceColumn: platform_key
		summarizeBy: none

	/// Metrics
	column impressions
		dataType: int64
		formatString: #,##0
		lineageTag: 00000000-0000-0000-0000-000000000085
		sourceColumn: impressions
		summarizeBy: sum

	column clicks
		dataType: int64
		formatString: #,##0
		lineageTag: 00000000-0000-0000-0000-000000000086
		sourceColumn: clicks
		summarizeBy: sum

	column ad_revenue
		dataType: decimal
		formatString: \$#,##0.00;(\$#,##0.00);\$#,##0.00
		lineageTag: 00000000-0000-0000-0000-000000000087
		sourceColumn: ad_revenue
		summarizeBy: sum

	/// ─────────────────────────────────────────────────────────────────────
	/// ADVERTISING MEASURES
	/// ─────────────────────────────────────────────────────────────────────

	measure 'Ad Revenue' = SUM(fct_ad[ad_revenue])
		formatString: \$#,##0;(\$#,##0);\$#,##0
		lineageTag: 00000000-0000-0000-0000-000000000088

	measure 'Ad Impressions' = SUM(fct_ad[impressions])
		formatString: #,##0
		lineageTag: 00000000-0000-0000-0000-000000000089

	measure 'Ad Clicks' = SUM(fct_ad[clicks])
		formatString: #,##0
		lineageTag: 00000000-0000-0000-0000-00000000008a

	measure 'CTR %' = 
		DIVIDE(
		    [Ad Clicks],
		    [Ad Impressions],
		    0
		) * 100
		formatString: 0.00\%;-0.00\%;0.00\%
		lineageTag: 00000000-0000-0000-0000-00000000008b

	measure eCPM = 
		DIVIDE(
		    [Ad Revenue],
		    [Ad Impressions],
		    0
		) * 1000
		formatString: \$#,##0.00;(\$#,##0.00);\$#,##0.00
		lineageTag: 00000000-0000-0000-0000-00000000008c

	partition fct_ad = entity
		mode: directLake
		source
			entityName: fct_ad
			schemaName: gold
			expressionSource: 'DirectLake-lh_hearst_gold'

